# Generated by Django 3.0.4 on 2020-03-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_userprofile_tex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tex',
            new_name='extrainfo',
        ),
    ]
